/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GooGol;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import javax.swing.ComboBoxModel;

/**
 *
 * @author umarazif
 */
public class CurrencyExchangeGUI extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyExchangeGUI
     */
    public CurrencyExchangeGUI() {
        initComponents();
    }

    public CurrencyExchangeGUI(String in) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        String[] input = in.split(" ");
        for (int j = 0; j < input.length-1; j++) {
            for (int i = 0; i < input[j].length(); i++) {
                if (Character.isDigit(input[j].charAt(i))) {
                    jTextField1.setText(jTextField1.getText() + in.charAt(i));
                }
            }
            if (input[j].toUpperCase().contains("MYR")) {
                jComboBox1.setSelectedItem("MYR");
            } else if (input[j].toUpperCase().contains("SGD")) {
                jComboBox1.setSelectedItem("SGD");
            } else if (input[j].toUpperCase().contains("VND")) {
                jComboBox1.setSelectedItem("VND");
            } else if (input[j].toUpperCase().contains("IDR")) {
                jComboBox1.setSelectedItem("IDR");
            } else if (input[j].toUpperCase().contains("PHP")) {
                jComboBox1.setSelectedItem("PHP");
            } else if (input[j].toUpperCase().contains("THB")) {
                jComboBox1.setSelectedItem("THB");
            } else if (input[j].toUpperCase().contains("KHR")) {
                jComboBox1.setSelectedItem("KHR");
            } else if (input[j].toUpperCase().contains("LAK")) {
                jComboBox1.setSelectedItem("LAK");
            } else if (input[j].toUpperCase().contains("MMK")) {
                jComboBox1.setSelectedItem("MMK");
            } else if (input[j].toUpperCase().contains("BND")) {
                jComboBox1.setSelectedItem("BND");
            } else if (input[j].toUpperCase().contains("USD")) {
                jComboBox1.setSelectedItem("USD");
            }
        }
        for (int j=0; j < input.length; j++){
             if (input[j].toUpperCase().contains("MYR")) {
                jComboBox2.setSelectedItem("MYR");
            } else if (input[j].toUpperCase().contains("SGD")) {
                jComboBox2.setSelectedItem("SGD");
            } else if (input[j].toUpperCase().contains("VND")) {
                jComboBox2.setSelectedItem("VND");
            } else if (input[j].toUpperCase().contains("IDR")) {
                jComboBox2.setSelectedItem("IDR");
            } else if (input[j].toUpperCase().contains("PHP")) {
                jComboBox2.setSelectedItem("PHP");
            } else if (input[j].toUpperCase().contains("THB")) {
                jComboBox2.setSelectedItem("THB");
            } else if (input[j].toUpperCase().contains("KHR")) {
                jComboBox2.setSelectedItem("KHR");
            } else if (input[j].toUpperCase().contains("LAK")) {
                jComboBox2.setSelectedItem("LAK");
            } else if (input[j].toUpperCase().contains("MMK")) {
                jComboBox2.setSelectedItem("MMK");
            } else if (input[j].toUpperCase().contains("BND")) {
                jComboBox2.setSelectedItem("BND");
            } else if (input[j].toUpperCase().contains("USD")) {
                jComboBox2.setSelectedItem("USD");
            }
        }
        jButton1.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        jComboBox1.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYR", "SGD", "VND", "IDR", "PHP", "THB", "KHR", "LAK", "MMK", "BND", "USD" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        jLabel1.setText("to");

        jComboBox2.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYR", "SGD", "VND", "IDR", "PHP", "THB", "KHR", "LAK", "MMK", "BND", "USD" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton1.setFont(new java.awt.Font("Product Sans", 1, 13)); // NOI18N
        jButton1.setText("CONVERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Original Currency
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // Output Currency
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Button CONVERT
        String original = (String) jComboBox1.getSelectedItem();
        String converted = (String) jComboBox2.getSelectedItem();
        double amount = Double.parseDouble(jTextField1.getText());
        if (original.contentEquals(converted)) {
            jLabel2.setText(converted + " " + Double.toString(amount));
        } else {
            try {
                Scanner input = new Scanner(new FileInputStream("Currency.txt"));
                double moneytemp = 0;
                while (input.hasNextLine()) {
                    String initial = input.nextLine();
                    String[] toringgit = initial.split(",");
                    for (int i = 0; i < toringgit.length; i++) {
                        if (original.equalsIgnoreCase(toringgit[i])) {
                            moneytemp = amount * Double.parseDouble(toringgit[i + 1]);
                        }
                    }
                }
                Scanner input1 = new Scanner(new FileInputStream("Currency2.txt"));
                double moneyfinal = 0;
                while (input1.hasNextLine()) {
                    String ori = input1.nextLine();
                    String[] moneyarray = ori.split(",");
                    for (int i = 0; i < moneyarray.length; i++) {
                        if (converted.equalsIgnoreCase(moneyarray[i])) {
                            moneyfinal = moneytemp * Double.parseDouble(moneyarray[i + 1]);
                        }
                    }
                }
                jLabel2.setText(converted + " " + Double.toString(moneyfinal));

                input.close();
            } catch (FileNotFoundException e) {
                System.out.println("File Not Found!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyExchangeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
